services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: agentic-rag-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - .:/app

    depends_on:
      - qdrant

    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest

    container_name: qdrant

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: